url: http://tgm-hit.github.io
baseurl: /BestShift/

# Site settings
title: BestShift
email: daniel@melichar.me
description: "Diplomaprojekt BestShift of the deparment for Information technology at the TGM in Vienna"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 0099ff
  secondary: 000
  secondary-dark: 000066

# Team names, titles and social links
people:
- name: Bozkurt H&uuml;seyin
  pic: default_profile
  position: Verbrauchsanalyse
  social: Zust&auml;ndig f&uuml;r die Darstellung des Spritverbrauchs &uuml;ber Zeit
    - title: github
      url: https://github.com/hbozkurt-tgm
    - title: facebook
      url: https://www.facebook.com/HDB57

- name: Faiku Fitim
  pic: default_profile
  position: Fahrgastkomfort
  social: Zust&auml;ndig f&uuml;r die Darstellung der Sensordaten zur ermittlung des Fahrgastkomforts.
    - title: github
      url: #
    - title: facebook
      url: #
    - title: xing
      url: #

- name: Melichar Daniel
  pic: default_profile
  position: Data Management - Analysis / Product Owner
  social: Zust&auml;ndig f&uuml;r die Datenbank und die Lesbarkeit der darin enthaltenen Daten.
    - title: github
      url: https://www.github.com/dmelichar-tgm
    - title: facebook
      url: https://www.facebook.com/daniel.melichar.1
    - title: xing
      url: https://www.xing.com/profile/Daniel_Melichar3

- name: Perny Tobias
  pic: default_profile
  position: Hardware und Sensorik
  social: Zust&auml;ndig f&uuml;r den Bau des Car-PC's und das auslesen der Sensordaten.
    - title: github
      url: #
    - title: facebook
      url: #
    - title: xing
      url: #

- name: Simsek Raphael
  pic: default_profile
  position: Schaltvorhersage
  social: Zust&auml;ndig f&uuml;r die Berechnung des Zeitpunkts des besten Schaltvorgangs.
    - title: github
      url: https://github.com/rsimsek-tgm
    - title: facebook
      url: https://www.facebook.com/raphael.simsek
    - title: xing
      url: https://www.xing.com/profile/Raphael_Simse



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/tgm-hit

# Postal address (add as many lines as necessary)
address:
  - line: Wexstra&szlig;e 19-23
  - line: 1200 Vienna, Austria

# Build settings
markdown: kramdown
permalink: pretty
encoding: utf-8